wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    - 1: test_acc
      5: 1
      6:
      - 1
    python_version: 3.9.7
    start_time: 1648498339
    t:
      1:
      - 1
      - 9
      - 41
      3:
      - 7
      4: 3.9.7
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
c_hidden:
  desc: null
  value: 64
c_in:
  desc: null
  value: 21
c_out:
  desc: null
  value: 1
dropout:
  desc: null
  value: 0.3
num_layers:
  desc: null
  value: 3
